name: absa project
desc: Train and evaluate
cmd: python3 main_llama.py "alexcadillon/SemEval2014Task4" "laptops" "huggyllama/llama-7b" "baffo32/decapoda-research-llama-7B-hf" "absaL-llama7" --input ${DATA} 
env:
  python:
   type: manual
   version: 3.11
   requirements-file: requirements.txt
   local-paths:
      - utils.py
      - main_llama.py
inputs:
  - prompts_absa.json: DATA
cloud-instance-type: g2.1